import { z } from 'zod';
import { localeSchema } from './common.js';

/**
 * Editorial content and inbound messages — the two things on the site that are written by
 * people rather than generated by the marketplace.
 *
 * Both are deliberately plain. A blog post is a title and text, not a rich-text document: a
 * WYSIWYG editor would mean shipping a serialisation format, a sanitiser and an editor bundle to
 * a client whose whole budget is 200 KB, for content that is announcements and advisories.
 */

// ---------------------------------------------------------------------------
// Blog
// ---------------------------------------------------------------------------

export const postStatusSchema = z.enum(['draft', 'published']);
export type PostStatus = z.infer<typeof postStatusSchema>;

/**
 * URL-safe, and generated from the title when the author does not supply one.
 *
 * Latin-only on purpose: a Bangla title transliterates to nothing useful, so those posts get a
 * dated fallback slug rather than a URL full of percent escapes.
 */
export const slugSchema = z
  .string()
  .trim()
  .toLowerCase()
  .min(3)
  .max(90)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'use lowercase letters, numbers and hyphens');

export const createPostSchema = z.object({
  title: z.string().trim().min(4).max(140),
  slug: slugSchema.optional(),
  /** Shown in the list. Generated from the body when omitted. */
  excerpt: z.string().trim().max(300).optional(),
  /** Plain text; blank lines separate paragraphs. */
  body: z.string().trim().min(20).max(20_000),
  coverImage: z.string().trim().max(300).optional(),
  status: postStatusSchema.default('draft'),
  locale: localeSchema.default('bn'),
  tags: z.array(z.string().trim().min(2).max(30)).max(6).default([]),
});
export type CreatePostInput = z.infer<typeof createPostSchema>;

/** Every field optional — an edit that only changes the status is a normal thing to do. */
export const updatePostSchema = createPostSchema.partial().refine(
  (v) => Object.keys(v).length > 0,
  'no fields to update',
);
export type UpdatePostInput = z.infer<typeof updatePostSchema>;

export const postQuerySchema = z.object({
  tag: z.string().trim().max(30).optional(),
  /** Admin-only; a public caller always gets published posts whatever they ask for. */
  status: postStatusSchema.optional(),
  limit: z.coerce.number().int().min(1).max(50).default(10),
  cursor: z.string().optional(),
});

export interface PostDto {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  /** Present on the detail response only — the list would be enormous with every body in it. */
  body?: string;
  coverImage?: string;
  status: PostStatus;
  locale: 'bn' | 'en';
  tags: string[];
  authorName: string;
  publishedAt?: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Contact
// ---------------------------------------------------------------------------

/**
 * Stored rather than emailed.
 *
 * A contact form that sends mail is a contact form that silently loses messages the day the mail
 * provider stops working — which is the situation this project is in right now. Writing to the
 * database means the message survives regardless, and the admin reads it in one place.
 */
export const contactMessageSchema = z.object({
  name: z.string().trim().min(2).max(80),
  email: z.string().trim().toLowerCase().email().max(160),
  subject: z.string().trim().min(3).max(140),
  message: z.string().trim().min(10).max(4_000),
});
export type ContactMessageInput = z.infer<typeof contactMessageSchema>;

export const contactStatusSchema = z.enum(['new', 'read', 'archived']);
export type ContactStatus = z.infer<typeof contactStatusSchema>;

export interface ContactMessageDto {
  id: string;
  name: string;
  email: string;
  subject: string;
  message: string;
  status: ContactStatus;
  createdAt: string;
}
